Search double tap
MozillaSocial/mozilla-social-android pull request #432
Opened 2024-01-30 21:52 UTC by JohnOberhauser

- Making it so if you tap the search tab icon while it's already selected, you will be sent to the search screen
- Increasing the height of the search bar.  The touch target was too small
- Fixing an issue with search bar alignment between the discover screen and the search screen

2024-01-30 22:12 UTC, devotaaabel requested changes
I think you want to use [gestures](https://developer.android.com/jetpack/compose/touch-input/pointer-input/tap-and-press) for this

2024-01-30 22:31 UTC, JohnOberhauser commented
> I think you want to use [gestures](https://developer.android.com/jetpack/compose/touch-input/pointer-input/tap-and-press) for this

Moving conversation to slack thread

2024-01-31 17:27 UTC, devotaaabel approved these changes

2024-01-31 17:27 UTC, devotaaabel commented on app/src/main/java/org/mozilla/social/ui/bottombar/MoSoNavigationBar.kt
> +    val doubleTapDestination: Destination?
Can you add comments here for clarity?

2024-01-31 17:52 UTC, merged